language: node_js
node_js:
  - '8.10'
install: npm install
cache:
  directories:
    - node_modules
    - lib
    - src
script:
  - npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run deploy -- --stage dev
    on:
      branch: staging
  - provider: script
    skip_cleanup: true
    script: npm run deploy -- --stage prod
    on:
      branch: master
