service: combine

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  environment:
    SERVICE: ${self:service}
    STAGE: ${self:provider.stage}
    REGION: ${opt:region, self:provider.region}

plugins:
  - serverless-offline
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 2

package:
  exclude:
    - ./**
    - ./*.*
  include:
    - handler.js

functions:
  combine:
    handler: handler.app
    events:
      - http:
          method: POST
          path: combine
          cors: true
